import { EventInfo, EventType } from "../models";

export const events: EventInfo[] = [
	{
		id: "1",
		title: "Football match",
		description: "Football match between Barcelona and Real Madrid. This highly anticipated match will showcase the skills and talent of some of the best football players in the world. Don't miss out on this thrilling event!",
		date: "2021-09-01",
		type: EventType.sport,
		phoneNumber: "123456789",
		email: "xyx@gmail.pl",
		address: "Stadium",
		thumbnail: "/assets/football-match.jpeg",
	},
	{
		id: "2",
		title: "Music concert",
		description: "Live music concert by a popular band. Get ready to dance and sing along to your favorite songs as this talented band takes the stage. It's going to be an unforgettable night of music and entertainment!",
		date: "2021-09-05",
		type: EventType.cultural,
		phoneNumber: "987654321",
		email: "abc@gmail.com",
		address: "Concert Hall",
		thumbnail: "/assets/bike.jpg",
	},
	{
		id: "3",
		title: "Basketball game",
		description: "Basketball game between Lakers and Celtics. Witness the intense rivalry between these two legendary teams as they battle it out on the court. Expect high-flying dunks, clutch shots, and thrilling moments!",
		date: "2021-09-10",
		type: EventType.sport,
		phoneNumber: "555555555",
		email: "def@gmail.com",
		address: "Arena",
		thumbnail: "/assets/football-match.jpeg",
	},
	{
		id: "4",
		title: "Theater play",
		description: "Classic theater play by a renowned playwright. Immerse yourself in the world of theater as talented actors bring this timeless play to life. Experience the magic of live performances!",
		date: "2021-09-15",
		type: EventType.cultural,
		phoneNumber: "999999999",
		email: "ghi@gmail.com",
		address: "Theater",
		thumbnail: "/assets/theatre.jpg",
	},
	{
		id: "5",
		title: "Art exhibition",
		description: "Art exhibition showcasing contemporary artists. Explore the diverse and thought-provoking works of art created by talented contemporary artists. Expand your horizons and appreciate the beauty of artistic expression!",
		date: "2021-09-20",
		type: EventType.cultural,
		phoneNumber: "777777777",
		email: "jkl@gmail.com",
		address: "Art Gallery",
		thumbnail: "/assets/theatre.jpg",
	},
];
