import { EventInfo, EventType } from "../models";

export const events: EventInfo[] = [
  {
    id: "1",
    title: "Football match",
    description: "Football match between Barcelona and Real Madrid",
    date: "2021-09-01",
    type: EventType.sport,
    phoneNumber: "123456789",
    email: "xyx@gmail.pl",
    address: "Stadium",
    thumbnail: "/assets/football-match.jpeg",
  },
  {
    id: "2",
    title: "Music concert",
    description: "Live music concert by a popular band",
    date: "2021-09-05",
    type: EventType.cultural,
    phoneNumber: "987654321",
    email: "abc@gmail.com",
    address: "Concert Hall",
    thumbnail: "/assets/football-match.jpeg",
  },
  {
    id: "3",
    title: "Basketball game",
    description: "Basketball game between Lakers and Celtics",
    date: "2021-09-10",
    type: EventType.sport,
    phoneNumber: "555555555",
    email: "def@gmail.com",
    address: "Arena",
    thumbnail: "/assets/football-match.jpeg",
  },
  {
    id: "4",
    title: "Theater play",
    description: "Classic theater play by a renowned playwright",
    date: "2021-09-15",
    type: EventType.cultural,
    phoneNumber: "999999999",
    email: "ghi@gmail.com",
    address: "Theater",
    thumbnail: "/assets/football-match.jpeg",
  },
  {
    id: "5",
    title: "Art exhibition",
    description: "Art exhibition showcasing contemporary artists",
    date: "2021-09-20",
    type: EventType.cultural,
    phoneNumber: "777777777",
    email: "jkl@gmail.com",
    address: "Art Gallery",
    thumbnail: "/assets/football-match.jpeg",
  },
];
